package modelos;
// Generated 17/03/2019 04:22:32 PM by Hibernate Tools 4.3.1



/**
 * Apuesta generated by hbm2java
 */
public class Apuesta  implements java.io.Serializable {


     private Integer idApuesta;
     private int idPartido;
     private int idUsuarios;
     private int idResultado;
     private int idBoleteria;

    public Apuesta() {
    }

    public Apuesta(int idPartido, int idUsuarios, int idResultado, int idBoleteria) {
       this.idPartido = idPartido;
       this.idUsuarios = idUsuarios;
       this.idResultado = idResultado;
       this.idBoleteria = idBoleteria;
    }
   
    public Integer getIdApuesta() {
        return this.idApuesta;
    }
    
    public void setIdApuesta(Integer idApuesta) {
        this.idApuesta = idApuesta;
    }
    public int getIdPartido() {
        return this.idPartido;
    }
    
    public void setIdPartido(int idPartido) {
        this.idPartido = idPartido;
    }
    public int getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public int getIdResultado() {
        return this.idResultado;
    }
    
    public void setIdResultado(int idResultado) {
        this.idResultado = idResultado;
    }
    public int getIdBoleteria() {
        return this.idBoleteria;
    }
    
    public void setIdBoleteria(int idBoleteria) {
        this.idBoleteria = idBoleteria;
    }




}


