package modelos;
// Generated 17/03/2019 04:22:32 PM by Hibernate Tools 4.3.1



/**
 * Boleteria generated by hbm2java
 */
public class Boleteria  implements java.io.Serializable {


     private Integer idBoleteria;
     private int precio;
     private int cantidad;
     private int idUsuarios;

    public Boleteria() {
    }

    public Boleteria(int precio, int cantidad, int idUsuarios) {
       this.precio = precio;
       this.cantidad = cantidad;
       this.idUsuarios = idUsuarios;
    }
   
    public Integer getIdBoleteria() {
        return this.idBoleteria;
    }
    
    public void setIdBoleteria(Integer idBoleteria) {
        this.idBoleteria = idBoleteria;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }




}


