package modelos;
// Generated 17/03/2019 04:22:32 PM by Hibernate Tools 4.3.1



/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer idEquipo;
     private String nombEquipo;
     private int idTipoDeporte;

    public Equipo() {
    }

    public Equipo(String nombEquipo, int idTipoDeporte) {
       this.nombEquipo = nombEquipo;
       this.idTipoDeporte = idTipoDeporte;
    }
   
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
    public String getNombEquipo() {
        return this.nombEquipo;
    }
    
    public void setNombEquipo(String nombEquipo) {
        this.nombEquipo = nombEquipo;
    }
    public int getIdTipoDeporte() {
        return this.idTipoDeporte;
    }
    
    public void setIdTipoDeporte(int idTipoDeporte) {
        this.idTipoDeporte = idTipoDeporte;
    }




}


