package modelos;
// Generated 17/03/2019 04:22:32 PM by Hibernate Tools 4.3.1



/**
 * Ganadores generated by hbm2java
 */
public class Ganadores  implements java.io.Serializable {


     private Integer idGanadores;
     private int idRifa;
     private int idApuesta;

    public Ganadores() {
    }

    public Ganadores(int idRifa, int idApuesta) {
       this.idRifa = idRifa;
       this.idApuesta = idApuesta;
    }
   
    public Integer getIdGanadores() {
        return this.idGanadores;
    }
    
    public void setIdGanadores(Integer idGanadores) {
        this.idGanadores = idGanadores;
    }
    public int getIdRifa() {
        return this.idRifa;
    }
    
    public void setIdRifa(int idRifa) {
        this.idRifa = idRifa;
    }
    public int getIdApuesta() {
        return this.idApuesta;
    }
    
    public void setIdApuesta(int idApuesta) {
        this.idApuesta = idApuesta;
    }




}


