package modelos;
// Generated 17/03/2019 04:22:32 PM by Hibernate Tools 4.3.1



/**
 * Perfiles generated by hbm2java
 */
public class Perfiles  implements java.io.Serializable {


     private Integer idPerfiles;
     private String nombPerf;

    public Perfiles() {
    }

    public Perfiles(String nombPerf) {
       this.nombPerf = nombPerf;
    }
   
    public Integer getIdPerfiles() {
        return this.idPerfiles;
    }
    
    public void setIdPerfiles(Integer idPerfiles) {
        this.idPerfiles = idPerfiles;
    }
    public String getNombPerf() {
        return this.nombPerf;
    }
    
    public void setNombPerf(String nombPerf) {
        this.nombPerf = nombPerf;
    }




}


