package modelos;
// Generated 17/03/2019 04:22:32 PM by Hibernate Tools 4.3.1



/**
 * Rifa generated by hbm2java
 */
public class Rifa  implements java.io.Serializable {


     private Integer idRifa;
     private int idUsuarios;
     private String premio;
     private int idBoleteria;

    public Rifa() {
    }

    public Rifa(int idUsuarios, String premio, int idBoleteria) {
       this.idUsuarios = idUsuarios;
       this.premio = premio;
       this.idBoleteria = idBoleteria;
    }
   
    public Integer getIdRifa() {
        return this.idRifa;
    }
    
    public void setIdRifa(Integer idRifa) {
        this.idRifa = idRifa;
    }
    public int getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public String getPremio() {
        return this.premio;
    }
    
    public void setPremio(String premio) {
        this.premio = premio;
    }
    public int getIdBoleteria() {
        return this.idBoleteria;
    }
    
    public void setIdBoleteria(int idBoleteria) {
        this.idBoleteria = idBoleteria;
    }




}


