package modelos;
// Generated 17/03/2019 04:22:32 PM by Hibernate Tools 4.3.1



/**
 * TipoDeporte generated by hbm2java
 */
public class TipoDeporte  implements java.io.Serializable {


     private Integer idTipoDeporte;
     private String nombDepor;

    public TipoDeporte() {
    }

    public TipoDeporte(String nombDepor) {
       this.nombDepor = nombDepor;
    }
   
    public Integer getIdTipoDeporte() {
        return this.idTipoDeporte;
    }
    
    public void setIdTipoDeporte(Integer idTipoDeporte) {
        this.idTipoDeporte = idTipoDeporte;
    }
    public String getNombDepor() {
        return this.nombDepor;
    }
    
    public void setNombDepor(String nombDepor) {
        this.nombDepor = nombDepor;
    }




}


